version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/landlord
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - db
    command: bash -c "mvn spring-boot:run"

  frontend:
    build:
      context: ./react_frontend
      dockerfile: ../docker/react_frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: landlord
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data: