version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/landlord
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    command: bash -c "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"

  frontend:
    build:
      context: ./react_frontend
      dockerfile: ../docker/react_frontend/Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
      - PORT=4173
    command: npm run preview -- --host 0.0.0.0 --port 4173
    volumes:
      - ./react_frontend:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: landlord
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data:

  
networks:
  app-network:
    driver: bridge