package de.propadmin.rentalmanager.models;

import java.time.LocalDate;
import java.util.List;

import org.springframework.boot.autoconfigure.security.SecurityProperties.User;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter @Setter
public class Landlord {

    @Id
    private Long id;
    private UserAccount userAccount;
    private String name;
    private String phoneNumber;

    private String licenseKey;
    private LocalDate licenseExpirationDate;

    @OneToMany(mappedBy = "landlord")
    @JsonManagedReference
    private List<RealEstateObject> realEstateObjects;

    @OneToMany(mappedBy = "landlord")
    @JsonManagedReference
    private List<Contract> contracts;

    @OneToMany(mappedBy = "landlord")
    @JsonManagedReference
    private List<Ticket> tickets;

    @OneToMany(mappedBy = "landlord")
    @JsonManagedReference
    private List<FrameworkContract> frameworkContracts;

    public boolean isLicenseValid() {
        return licenseExpirationDate != null && LocalDate.now().isBefore(licenseExpirationDate);
    }

    // Getters and setters generated by Lombok
}

